
# Vagrantfile — Ubuntu 22.04 (jammy)
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "atomic-vm"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  # private network (удобно для ansible)
  config.vm.network "private_network", ip: "192.168.56.10"

  # синхронизация (по желанию)
  config.vm.synced_folder ".", "/vagrant", disabled: false

  # Используем ansible provisioner (требует Ansible на хосте).
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.tags = ENV['ANSIBLE_TAGS'] if ENV['ANSIBLE_TAGS']
    ansible.inventory_path = "ansible/inventory.ini"
    ansible.limit = "all"
  end

end
